matrix:
  include:
  - os: osx
    language: node_js
    node_js: node
    env:
    - BUILD_PLATFORM=osx64
  - os: linux
    dist: trusty
    language: node_js
    node_js: node
    env:
    - BUILD_PLATFORM=linux64
install:
- cd src
- npm install
- cd $TRAVIS_BUILD_DIR/script
- npm install
- npm run build $BUILD_PLATFORM
script:
- npm test
before_deploy:
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd script/build/iSparta
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r -9 iSparta-$BUILD_PLATFORM.zip $BUILD_PLATFORM/ ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -r -9 iSparta-$BUILD_PLATFORM.zip $BUILD_PLATFORM/ ; fi
- mv iSparta-$BUILD_PLATFORM.zip $TRAVIS_BUILD_DIR/build/
deploy:
  provider: releases
  api_key:
    secure: GxcAm6BJdOJRlke8Kn5ENCSSa+zOlGZ8Jo8vr0LQxngVCTBrjsFVIu8flOiZW580oopiIKRAlshplFU1jjp1z4PoHNOrNFy/6qsza9UsQ/4hrNPJUP8fZMuXqfeJ0qm9A0Pz17NI2ou66HCzqQvaMpwdeMaxmFS9iiQzV0QSazM=
  file_glob: true
  file: $TRAVIS_BUILD_DIR/build/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: iSparta/iSparta
cache:
  directories:
  - script/cache
notifications:
  email: false
